import { Typography } from "@mui/material";
import Head from "next/head";
import Login from "../components/Login";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <Typography variant="h3">MSys</Typography>
      </header>
      <Login />
      <footer>
        <div style={{ margin: "10rem 0 0 0" }}>
          <Typography variant="h5">© MSys Technologies</Typography>
        </div>
      </footer>
    </div>
  );
}
